export const movies = [
  {
    id: 1,
    title: "Back to the Future",
    year: 1985,
    genre: "Sci-Fi",
    director: "Robert Zemeckis",
    description: "A teenager is accidentally sent 30 years into the past.",
    image: "/movies/back-to-the-future.jpg",
  },
  {
    id: 2,
    title: "Jaws",
    year: 1975,
    genre: "Horror",
    director: "Steven Spielberg",
    description: "A giant man-eating shark terrorizes a beach town.",
    image: "/movies/jaws.jpg",
  },
  {
    id: 3,
    title: "Jurassic Park",
    year: 1993,
    genre: "Adventure",
    director: "Steven Spielberg",
    description: "Scientists bring dinosaurs back to life in a theme park.",
    image: "/movies/jurassic-park.jpg",
  },
  {
    id: 4,
    title: "Ghostbusters",
    year: 1984,
    genre: "Comedy",
    director: "Ivan Reitman",
    description: "Three scientists start a ghost-catching business.",
    image: "/movies/ghostbusters.jpg",
  },
  {
    id: 5,
    title: "Blade Runner",
    year: 1982,
    genre: "Sci-Fi",
    director: "Ridley Scott",
    description: "A blade runner must pursue and terminate four replicants.",
    image: "/movies/blade-runner.jpg",
  },
  {
    id: 6,
    title: "E.T. the Extra-Terrestrial",
    year: 1982,
    genre: "Sci-Fi",
    director: "Steven Spielberg",
    description: "A boy befriends a stranded friendly and cute alien.",
    image: "/movies/e-t-the-extra-terrestrial.jpg",
  },
  {
    id: 7,
    title: "The Terminator",
    year: 1984,
    genre: "Action",
    director: "James Cameron",
    description: "A cyborg is sent back in time to kill a woman.",
    image: "/movies/the-terminator.jpg",
  },
  {
    id: 8,
    title: "Aliens",
    year: 1986,
    genre: "Sci-Fi",
    director: "James Cameron",
    description: "Ripley returns to fight extraterrestrial creatures.",
    image: "/movies/aliens.jpg",
  },
  {
    id: 9,
    title: "Die Hard",
    year: 1988,
    genre: "Action",
    director: "John McTiernan",
    description: "An NYPD officer tries to save hostages in a skyscraper.",
    image: "/movies/die-hard.jpg",
  },
  {
    id: 10,
    title: "The Breakfast Club",
    year: 1985,
    genre: "Drama",
    director: "John Hughes",
    description: "Five high school students bond during detention.",
    image: "/movies/the-breakfast-club.jpg",
  },
  {
    id: 11,
    title: "Top Gun",
    year: 1986,
    genre: "Action",
    director: "Tony Scott",
    description: "Fighter pilots compete at an elite training school.",
    image: "/movies/top-gun.jpg",
  },
  {
    id: 12,
    title: "The Goonies",
    year: 1985,
    genre: "Adventure",
    director: "Richard Donner",
    description:
      "A group of kids search for pirate treasure and dangerous challenges.",
    image: "/movies/the-goonies.jpg",
  },
  {
    id: 13,
    title: "Raiders of the Lost Ark",
    year: 1981,
    genre: "Adventure",
    director: "Steven Spielberg",
    description: "Indiana Jones searches for the Ark of the Covenant.",
    image: "/movies/raiders-of-the-lost-ark.jpg",
  },
  {
    id: 14,
    title: "The Last Crusade",
    year: 1989,
    genre: "Adventure",
    director: "Steven Spielberg",
    description:
      "Indiana Jones searches for the Holy Grail and faces his father.",
    image: "/movies/indiana-jones-and-the-last-crusade.jpg",
  },
  {
    id: 15,
    title: "RoboCop",
    year: 1987,
    genre: "Sci-Fi",
    director: "Paul Verhoeven",
    description: "A murdered police officer is revived as a cyborg.",
    image: "/movies/robocop.jpg",
  },
  {
    id: 16,
    title: "The Shining",
    year: 1980,
    genre: "Horror",
    director: "Stanley Kubrick",
    description: "A writer becomes obsessed at an isolated hotel.",
    image: "/movies/the-shining.jpg",
  },
  {
    id: 17,
    title: "Scarface",
    year: 1983,
    genre: "Drama",
    director: "Brian De Palma",
    description: "A Cuban immigrant rises to power in the drug trade in Miami.",
    image: "/movies/scarface.jpg",
  },
  {
    id: 18,
    title: "Batman",
    year: 1989,
    genre: "Action",
    director: "Tim Burton",
    description:
      "Batman faces the Joker in Gotham City in a dark and gritty retelling.",
    image: "/movies/batman.jpg",
  },
  {
    id: 19,
    title: "Rocky IV",
    year: 1985,
    genre: "Drama",
    director: "Sylvester Stallone",
    description:
      "Rocky fights a Soviet boxer in the ring in a story of perseverance.",
    image: "/movies/rocky-iv.jpg",
  },
  {
    id: 20,
    title: "Gremlins",
    year: 1984,
    genre: "Comedy",
    director: "Joe Dante",
    description:
      "Strange creatures wreak havoc on a town in a darkly comedic tale.",
    image: "/movies/gremlins.jpg",
  },
  {
    id: 21,
    title: "Ferris Bueller's Day Off",
    year: 1986,
    genre: "Comedy",
    director: "John Hughes",
    description: "A teenager skips school and goes on a wild adventure.",
    image: "/movies/ferris-bueller-s-day-off.jpg",
  },
  {
    id: 22,
    title: "Poltergeist",
    year: 1982,
    genre: "Horror",
    director: "Tobe Hooper",
    description:
      "A family's home is invaded by spirits in a terrifying ordeal.",
    image: "/movies/poltergeist.jpg",
  },
  {
    id: 23,
    title: "Big Trouble in Little China",
    year: 1986,
    genre: "Adventure",
    director: "John Carpenter",
    description: "A truck driver helps rescue a kidnapped woman.",
    image: "/movies/big-trouble-in-little-china.jpg",
  },
  {
    id: 24,
    title: "Stand by Me",
    year: 1986,
    genre: "Drama",
    director: "Rob Reiner",
    description: "Four boys go on a journey to find a missing body.",
    image: "/movies/stand-by-me.jpg",
  },
  {
    id: 25,
    title: "The Karate Kid",
    year: 1984,
    genre: "Drama",
    director: "John G. Avildsen",
    description:
      "A teenager learns karate from a wise mentor to overcome bullying.",
    image: "/movies/the-karate-kid.jpg",
  },
  {
    id: 26,
    title: "Beetlejuice",
    year: 1988,
    genre: "Comedy",
    director: "Tim Burton",
    description: "A mischievous ghost helps a couple haunt their home.",
    image: "/movies/beetlejuice.jpg",
  },
  {
    id: 27,
    title: "Predator",
    year: 1987,
    genre: "Action",
    director: "John McTiernan",
    description:
      "A team faces an alien hunter in the jungle in a high-stakes thriller.",
    image: "/movies/predator.jpg",
  },
  {
    id: 28,
    title: "The Thing",
    year: 1982,
    genre: "Horror",
    director: "John Carpenter",
    description:
      "A shape-shifting alien terrorizes researchers in an isolated Antarctic.",
    image: "/movies/the-thing.jpg",
  },
  {
    id: 29,
    title: "The NeverEnding Story",
    year: 1984,
    genre: "Fantasy",
    director: "Wolfgang Petersen",
    description: "A boy discovers a magical neverending story.",
    image: "/movies/the-neverending-story.jpg",
  },
  {
    id: 30,
    title: "Star Wars",
    year: 1977,
    genre: "Sci-Fi",
    director: "George Lucas",
    description:
      "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot and a Wookiee.",
    image: "/movies/star-wars.jpg",
  },
];
